"""Frozen PIT-17 canonical semantic fact schema constants."""

SCHEMA_VERSION = "pit17-semantic-facts-v1"

SCOPE_LEVELS = {
    "OBSERVATION": 0,
    "SESSION": 1,
    "TASK": 2,
    "DOMAIN": 3,
    "WORKFLOW": 4,
    "GLOBAL": 5,
}

VIOLATION_CLASSES = (
    "UNSUPPORTED_CONFLICT_RESOLUTION",
    "UNSUPPORTED_NUMERIC_THRESHOLD",
    "UNSUPPORTED_TEMPORAL_RULE",
    "UNSUPPORTED_FALLBACK_POLICY",
    "UNSUPPORTED_SCOPE_GENERALIZATION",
    "EVIDENCE_GROUNDING_FAILURE",
)
