"""M5 llama.cpp runtime/export qualification.

The high-fidelity GGUF path is always adjudicated before any quantization target
is allowed to run. Quantized artifacts cannot rescue a failed F16 conversion or
runtime-parity result.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

from .canonical import sha256_file, sha256_object
from .errors import (
    LlamaCppConversionError,
    LlamaCppLockError,
    RuntimeParityError,
)
from .io import atomic_write_json, atomic_write_text
from .loader import load_experiment_config, load_model_profile
from .m2 import run_m2_qualification
from .reasoning import ReasoningCapability, capability_from_profile, normalize_tagged_output


@dataclass(frozen=True)
class M5Result:
    status: str
    run_id: str
    run_dir: Path
    llama_cpp_commit: str
    high_fidelity_dtype: str
    high_fidelity_parity: bool
    quantized_targets: tuple[str, ...]
    quantized_passed: int
    gates_passed: int
    gates_total: int
    adjudication_hash: str
    public_bulk_download_started: bool

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "run_id": self.run_id,
            "run_dir": str(self.run_dir),
            "llama_cpp_commit": self.llama_cpp_commit,
            "high_fidelity_dtype": self.high_fidelity_dtype,
            "high_fidelity_parity": self.high_fidelity_parity,
            "quantized_targets": list(self.quantized_targets),
            "quantized_passed": self.quantized_passed,
            "gates_passed": self.gates_passed,
            "gates_total": self.gates_total,
            "adjudication_hash": self.adjudication_hash,
            "public_bulk_download_started": self.public_bulk_download_started,
        }


def run_m5_qualification(
    config_path: str | Path,
    repo_root: str | Path,
    runs_root: str | Path,
    *,
    llama_source: str | Path,
    llama_cli: str | Path,
    llama_quantize: str | Path,
    converter_python: str | Path,
    build_manifest: str | Path,
) -> M5Result:
    repo_root = Path(repo_root).resolve()
    config_path = Path(config_path)
    if not config_path.is_absolute():
        config_path = (repo_root / config_path).resolve()
    runs_root = Path(runs_root)
    if not runs_root.is_absolute():
        runs_root = (repo_root / runs_root).resolve()

    config = load_experiment_config(config_path, repo_root)
    profile = load_model_profile(config, repo_root)
    m4_evidence = _read_object(
        repo_root / "artifacts/model-training-pipeline/m4/M4_QUALIFICATION_EVIDENCE.json"
    )
    if m4_evidence.get("verdict") != "PASS":
        raise RuntimeParityError("M4 prerequisite is not PASS")

    lock_path = repo_root / "docs/model-training-pipeline/runtime/llama_cpp.lock.json"
    lock = _read_object(lock_path)
    llama_source = Path(llama_source).resolve()
    llama_cli = Path(llama_cli).resolve()
    llama_quantize = Path(llama_quantize).resolve()
    converter_python = Path(converter_python).resolve()
    build_manifest = Path(build_manifest).resolve()

    lock_evidence = verify_llama_cpp_lock(
        lock=lock,
        source_dir=llama_source,
        llama_cli=llama_cli,
        llama_quantize=llama_quantize,
        converter_python=converter_python,
        build_manifest=build_manifest,
    )

    # M5 consumes a canonical artifact regenerated by the already-qualified M2
    # path. This is fixture-scale and does not touch bulk corpora.
    m2 = run_m2_qualification(config_path, repo_root, runs_root)
    canonical_hf = m2.run_dir / "canonical_hf"
    if not canonical_hf.is_dir():
        raise RuntimeParityError("M2 canonical HF artifact is missing")

    m5_dir = m2.run_dir / "m5"
    m5_dir.mkdir(parents=True, exist_ok=False)
    atomic_write_json(m5_dir / "llama_cpp_lock_evidence.json", lock_evidence)

    converter = llama_source / lock["converter"]["path"]
    capability = _run(
        [str(converter_python), str(converter), "--print-supported-models"],
        cwd=llama_source,
        label="converter capability inspection",
        combine=True,
    )
    required_arch = lock["converter"]["required_supported_architecture"]
    if required_arch not in capability["combined"]:
        raise LlamaCppConversionError(
            f"pinned converter does not advertise {required_arch}"
        )
    atomic_write_text(m5_dir / "converter_supported_models.txt", capability["combined"])

    cli_version = _run([str(llama_cli), "--version"], label="llama-cli version", combine=True)
    cli_help = _run([str(llama_cli), "--help"], label="llama-cli help", combine=True)
    for required_flag in ("--no-display-prompt", "--simple-io", "--log-disable"):
        if required_flag not in cli_help["combined"]:
            raise LlamaCppLockError(f"pinned llama-cli missing required flag {required_flag}")
    atomic_write_text(m5_dir / "llama_cli_version.txt", cli_version["combined"])

    hf_baseline = run_hf_fixture(
        canonical_hf=canonical_hf,
        fixture_path=repo_root / config.fixture_set,
        inference=config.inference,
    )
    atomic_write_json(m5_dir / "hf_baseline.json", hf_baseline)
    gguf_dir = m5_dir / "gguf"
    gguf_dir.mkdir()
    high_fidelity = str(config.export["gguf"]["high_fidelity"]).lower()
    if high_fidelity != lock["high_fidelity_policy"]:
        raise LlamaCppLockError(
            f"config high_fidelity={high_fidelity} differs from lock={lock['high_fidelity_policy']}"
        )
    if high_fidelity not in {"f16", "bf16"}:
        raise LlamaCppConversionError(
            f"M5 high-fidelity qualification only permits f16/bf16, got {high_fidelity}"
        )

    hf_gguf = gguf_dir / f"model-{high_fidelity}.gguf"
    conversion = _run(
        [
            str(converter_python),
            str(converter),
            str(canonical_hf),
            "--outtype",
            high_fidelity,
            "--outfile",
            str(hf_gguf),
        ],
        cwd=llama_source,
        label=f"HF to {high_fidelity} GGUF conversion",
        combine=True,
    )
    atomic_write_text(m5_dir / "conversion_high_fidelity.log", conversion["combined"])
    high_manifest = build_gguf_manifest(hf_gguf, high_fidelity)

    hf_runtime = run_llama_fixture(
        llama_cli=llama_cli,
        model_path=hf_gguf,
        hf_baseline=hf_baseline,
        inference=config.inference,
    )
    high_parity = evaluate_runtime_parity(hf_baseline, hf_runtime)
    atomic_write_json(m5_dir / "runtime_high_fidelity.json", hf_runtime)
    atomic_write_json(m5_dir / "parity_high_fidelity.json", high_parity)
    atomic_write_json(m5_dir / "manifest_high_fidelity.json", high_manifest)

    if not high_parity["pass"]:
        raise RuntimeParityError(
            "high-fidelity GGUF parity failed; quantization is forbidden"
        )

    reasoning_mapping = qualify_reasoning_runtime_mapping(
        profile=profile,
        repo_root=repo_root,
        artifact_hash=high_manifest["aggregate_hash"],
    )
    atomic_write_json(m5_dir / "reasoning_runtime_mapping.json", reasoning_mapping)

    # Quantization is intentionally unreachable until the F16/BF16 gate above
    # has passed.
    quant_targets = tuple(str(x).lower() for x in config.export["gguf"].get("quantize", []))
    quant_results: dict[str, Any] = {}
    for target in quant_targets:
        quant_results[target] = run_quantized_target(
            target=target,
            source_gguf=hf_gguf,
            gguf_dir=gguf_dir,
            llama_quantize=llama_quantize,
            llama_cli=llama_cli,
            hf_baseline=hf_baseline,
            inference=config.inference,
        )
        if not quant_results[target]["parity"]["pass"]:
            raise RuntimeParityError(f"quantized target {target} parity failed")
    atomic_write_json(m5_dir / "quantized_results.json", quant_results)

    gates = {
        "m4_prerequisite": m4_evidence.get("verdict") == "PASS",
        "m2_canonical_regenerated": m2.status == "PASS" and canonical_hf.is_dir(),
        "llama_cpp_exact_commit": lock_evidence["source_commit_match"],
        "converter_blob_match": lock_evidence["converter_blob_match"],
        "converter_capability_qwen2": required_arch in capability["combined"],
        "llama_cli_real_binary": bool(cli_version["combined"].strip()),
        "high_fidelity_conversion": bool(high_manifest["files"]),
        "high_fidelity_real_inference": hf_runtime["all_outputs_nonempty"],
        "high_fidelity_task_format_parity": high_parity["pass"],
        "reasoning_parser_mapping": reasoning_mapping["pass"],
        "quantization_after_high_fidelity_only": True,
        "all_required_quantized_targets": len(quant_results) == len(quant_targets)
        and all(item["parity"]["pass"] for item in quant_results.values()),
        "no_bulk_training": m2.public_bulk_download_started is False,
    }
    failed = [name for name, value in gates.items() if not value]
    adjudication = {
        "schema": "mindforge-model-pipeline-m5-adjudication-v1",
        "run_id": m2.run_id,
        "llama_cpp_lock": lock,
        "llama_cpp_lock_evidence": lock_evidence,
        "m2": {
            "canonical_directory_hash": m2.canonical_directory_hash,
            "adjudication_hash": m2.adjudication_hash,
        },
        "high_fidelity": {
            "dtype": high_fidelity,
            "artifact_manifest": high_manifest,
            "parity": high_parity,
        },
        "quantized_targets": quant_results,
        "reasoning_runtime_mapping": reasoning_mapping,
        "gates": {name: {"required": True, "pass": bool(value)} for name, value in gates.items()},
        "failed_required_gates": failed,
        "public_bulk_download_started": False,
        "verdict": "PASS" if not failed else "FAIL",
    }
    adjudication_hash = sha256_object(adjudication)
    atomic_write_json(
        m5_dir / "m5_adjudication.json",
        {**adjudication, "adjudication_hash": adjudication_hash},
    )
    if failed:
        raise RuntimeParityError(f"M5 adjudication failed gates: {failed}")

    result = M5Result(
        status="PASS",
        run_id=m2.run_id,
        run_dir=m2.run_dir,
        llama_cpp_commit=lock["commit_sha"],
        high_fidelity_dtype=high_fidelity,
        high_fidelity_parity=True,
        quantized_targets=quant_targets,
        quantized_passed=sum(item["parity"]["pass"] for item in quant_results.values()),
        gates_passed=len(gates),
        gates_total=len(gates),
        adjudication_hash=adjudication_hash,
        public_bulk_download_started=False,
    )
    atomic_write_json(m5_dir / "m5_result.json", result.to_dict())
    return result


def verify_llama_cpp_lock(
    *,
    lock: Mapping[str, Any],
    source_dir: Path,
    llama_cli: Path,
    llama_quantize: Path,
    converter_python: Path,
    build_manifest: Path,
) -> dict[str, Any]:
    for path in (source_dir, llama_cli, llama_quantize, converter_python, build_manifest):
        if not path.exists():
            raise LlamaCppLockError(f"required runtime path missing: {path}")

    commit = _run(
        ["git", "-C", str(source_dir), "rev-parse", "HEAD"],
        label="llama.cpp source commit",
    )["stdout"].strip()
    expected_commit = str(lock["commit_sha"])
    if commit != expected_commit:
        raise LlamaCppLockError(
            f"llama.cpp commit mismatch expected={expected_commit} actual={commit}"
        )

    converter = source_dir / str(lock["converter"]["path"])
    blob = git_blob_sha1(converter)
    expected_blob = str(lock["converter"]["git_blob_sha1"])
    if blob != expected_blob:
        raise LlamaCppLockError(
            f"converter blob mismatch expected={expected_blob} actual={blob}"
        )

    build = _read_object(build_manifest)
    expected_flags = list(lock["build"]["flags"])
    expected_targets = list(lock["build"]["targets"])
    if build.get("flags") != expected_flags:
        raise LlamaCppLockError("build manifest flags differ from runtime lock")
    if build.get("targets") != expected_targets:
        raise LlamaCppLockError("build manifest targets differ from runtime lock")
    if build.get("source_commit") != expected_commit:
        raise LlamaCppLockError("build manifest source commit differs from runtime lock")

    probe_script = Path(__file__).resolve().with_name("m5_converter_probe.py")
    converter_env = _run(
        [str(converter_python), str(probe_script)],
        label="converter environment import probe",
    )
    try:
        converter_probe = json.loads(converter_env["stdout"])
    except json.JSONDecodeError as error:
        raise LlamaCppLockError(f"cannot parse converter environment probe: {error}") from error
    if not isinstance(converter_probe, dict):
        raise LlamaCppLockError("converter environment probe must return an object")

    required_modules = ("torch", "transformers", "numpy", "sentencepiece", "protobuf", "gguf")
    missing = [
        name
        for name in required_modules
        if not isinstance(converter_probe.get(name), dict)
        or converter_probe[name].get("import_ok") is not True
    ]
    if missing:
        raise LlamaCppLockError(
            f"converter environment missing/import-failed modules: {missing}"
        )

    pip_freeze = _run(
        [str(converter_python), "-m", "pip", "freeze", "--all"],
        label="converter environment freeze",
    )["stdout"]
    freeze_lines = sorted(
        line.strip()
        for line in pip_freeze.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )
    if not freeze_lines:
        raise LlamaCppLockError("converter pip freeze is empty")
    converter_versions = {
        name: str(converter_probe[name].get("version"))
        for name in required_modules
    }

    return {
        "source_commit": commit,
        "expected_commit": expected_commit,
        "source_commit_match": commit == expected_commit,
        "converter_path": str(converter),
        "converter_git_blob_sha1": blob,
        "expected_converter_git_blob_sha1": expected_blob,
        "converter_blob_match": blob == expected_blob,
        "converter_sha256": sha256_file(converter),
        "llama_cli_sha256": sha256_file(llama_cli),
        "llama_quantize_sha256": sha256_file(llama_quantize),
        "build_manifest_hash": sha256_object(build),
        "build_flags": build["flags"],
        "build_targets": build["targets"],
        "converter_environment_versions": converter_versions,
        "converter_environment_probe": converter_probe,
        "converter_pip_freeze": freeze_lines,
        "converter_pip_freeze_hash": sha256_object(freeze_lines),
        "lock_hash": sha256_object(lock),
    }


def git_blob_sha1(path: Path) -> str:
    data = path.read_bytes()
    header = f"blob {len(data)}\0".encode("ascii")
    return hashlib.sha1(header + data).hexdigest()


def run_hf_fixture(
    *,
    canonical_hf: Path,
    fixture_path: Path,
    inference: Mapping[str, Any],
) -> dict[str, Any]:
    manifest_path = fixture_path / "manifest.json" if fixture_path.is_dir() else fixture_path
    fixture = _read_object(manifest_path)
    tasks = fixture.get("tasks")
    if not isinstance(tasks, list) or not tasks:
        raise RuntimeParityError("runtime fixture has no tasks")

    torch.manual_seed(int(inference["seed"]))
    torch.set_num_threads(1)
    tokenizer = AutoTokenizer.from_pretrained(
        canonical_hf, local_files_only=True, trust_remote_code=False
    )
    model = AutoModelForCausalLM.from_pretrained(
        canonical_hf,
        local_files_only=True,
        trust_remote_code=False,
        dtype=torch.float32,
    )
    model.eval()

    rows = []
    with torch.no_grad():
        for task in tasks:
            prompt_text = tokenizer.apply_chat_template(
                [{"role": "user", "content": task["prompt"]}],
                tokenize=False,
                add_generation_prompt=True,
            )
            encoded = tokenizer(
                prompt_text,
                return_tensors="pt",
                add_special_tokens=False,
            )
            generated = model.generate(
                **encoded,
                do_sample=False,
                max_new_tokens=int(inference["max_new_tokens"]),
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )
            new_ids = generated[0, encoded["input_ids"].shape[1] :]
            output = tokenizer.decode(new_ids, skip_special_tokens=True).strip()
            rows.append(
                {
                    "id": task["id"],
                    "type": task["type"],
                    "expected": task["expected"],
                    "prompt_text": prompt_text,
                    "prompt_hash": sha256_object(prompt_text),
                    "output": output,
                    "output_hash": sha256_object(output),
                    "format_valid": valid_runtime_output(output),
                    "task_success": task_success(task, output),
                }
            )
    del model
    return {
        "fixture_set_id": fixture.get("fixture_set_id"),
        "inference_contract": dict(inference),
        "rows": rows,
        "task_success_count": sum(row["task_success"] for row in rows),
        "all_outputs_nonempty": all(row["format_valid"] for row in rows),
        "task_vector": [bool(row["task_success"]) for row in rows],
        "accuracy": sum(row["task_success"] for row in rows) / len(rows),
    }


def run_llama_fixture(
    *,
    llama_cli: Path,
    model_path: Path,
    hf_baseline: Mapping[str, Any],
    inference: Mapping[str, Any],
) -> dict[str, Any]:
    rows = []
    for baseline in hf_baseline["rows"]:
        command = [
            str(llama_cli),
            "-m",
            str(model_path),
            "-p",
            baseline["prompt_text"],
            "-n",
            str(int(inference["max_new_tokens"])),
            "-c",
            str(int(inference["context_length"])),
            "--temp",
            str(float(inference["temperature"])),
            "--top-p",
            str(float(inference["top_p"])),
            "--top-k",
            str(int(inference["top_k"])),
            "--seed",
            str(int(inference["seed"])),
            "--threads",
            "2",
            "--no-display-prompt",
            "--simple-io",
            "--log-disable",
            "--no-perf",
        ]
        completed = _run(command, label=f"llama.cpp inference {baseline['id']}")
        output = strip_ansi(completed["stdout"]).strip()
        task = {
            "id": baseline["id"],
            "type": baseline["type"],
            "expected": baseline["expected"],
        }
        rows.append(
            {
                "id": baseline["id"],
                "expected": baseline["expected"],
                "output": output,
                "output_hash": sha256_object(output),
                "format_valid": valid_runtime_output(output),
                "task_success": task_success(task, output),
                "exact_text_equal_hf": output == baseline["output"],
            }
        )
    return {
        "model_path": str(model_path),
        "model_sha256": sha256_file(model_path),
        "rows": rows,
        "task_success_count": sum(row["task_success"] for row in rows),
        "all_outputs_nonempty": all(row["format_valid"] for row in rows),
        "task_vector": [bool(row["task_success"]) for row in rows],
        "accuracy": sum(row["task_success"] for row in rows) / len(rows),
        "exact_text_equal_count": sum(row["exact_text_equal_hf"] for row in rows),
    }


def evaluate_runtime_parity(
    hf_baseline: Mapping[str, Any],
    runtime: Mapping[str, Any],
) -> dict[str, Any]:
    hf_vector = list(hf_baseline["task_vector"])
    runtime_vector = list(runtime["task_vector"])
    pass_value = (
        bool(hf_baseline["all_outputs_nonempty"])
        and bool(runtime["all_outputs_nonempty"])
        and hf_vector == runtime_vector
        and float(hf_baseline["accuracy"]) == float(runtime["accuracy"])
    )
    return {
        "pass": pass_value,
        "hf_task_vector": hf_vector,
        "runtime_task_vector": runtime_vector,
        "hf_accuracy": hf_baseline["accuracy"],
        "runtime_accuracy": runtime["accuracy"],
        "format_parity": bool(hf_baseline["all_outputs_nonempty"])
        and bool(runtime["all_outputs_nonempty"]),
        "exact_text_equal_count": runtime["exact_text_equal_count"],
        "exact_text_required": False,
    }


def build_gguf_manifest(primary_path: Path, label: str) -> dict[str, Any]:
    if primary_path.is_file():
        paths = [primary_path]
        topology = "single_file"
    else:
        candidates = sorted(primary_path.parent.glob(primary_path.stem + "-*.gguf"))
        if not candidates:
            raise LlamaCppConversionError(f"GGUF artifact missing: {primary_path}")
        paths = candidates
        topology = "shard_set"

    files = [
        {
            "name": path.name,
            "size": path.stat().st_size,
            "sha256": sha256_file(path),
        }
        for path in paths
    ]
    return {
        "label": label,
        "topology": topology,
        "files": files,
        "aggregate_hash": sha256_object(files),
    }


def run_quantized_target(
    *,
    target: str,
    source_gguf: Path,
    gguf_dir: Path,
    llama_quantize: Path,
    llama_cli: Path,
    hf_baseline: Mapping[str, Any],
    inference: Mapping[str, Any],
) -> dict[str, Any]:
    mapping = {
        "q4_k_m": "Q4_K_M",
        "q8_0": "Q8_0",
    }
    if target not in mapping:
        raise LlamaCppConversionError(f"unsupported M5 quantization target {target}")
    output = gguf_dir / f"model-{target}.gguf"
    command = [
        str(llama_quantize),
        str(source_gguf),
        str(output),
        mapping[target],
    ]
    quant = _run(command, label=f"quantize {target}", combine=True)
    manifest = build_gguf_manifest(output, target)
    runtime = run_llama_fixture(
        llama_cli=llama_cli,
        model_path=output,
        hf_baseline=hf_baseline,
        inference=inference,
    )
    parity = evaluate_runtime_parity(hf_baseline, runtime)
    return {
        "quantizer_log_hash": sha256_object(quant["combined"]),
        "artifact_manifest": manifest,
        "runtime": runtime,
        "parity": parity,
    }


def qualify_reasoning_runtime_mapping(
    *,
    profile: Mapping[str, Any],
    repo_root: Path,
    artifact_hash: str,
) -> dict[str, Any]:
    base = capability_from_profile(profile)
    mapped = ReasoningCapability(
        supported=base.supported,
        training_format=base.training_format,
        transport_options=base.transport_options,
        visibility_modes=base.visibility_modes,
        effort_levels=base.effort_levels,
        supports_disable=base.supports_disable,
        supports_hide=base.supports_hide,
        native_runtime_support={
            **dict(base.native_runtime_support),
            "llama_cpp": "raw_stdout_tagged_text_parser",
        },
    )
    raw = "<think>llama.cpp parser mapping probe</think>\n<answer>42</answer>"
    visible = normalize_tagged_output(
        raw_text=raw,
        mode="visible",
        capability=mapped,
        profile=profile,
        runtime="llama.cpp-raw-stdout",
        model_artifact=f"gguf:{artifact_hash}",
        repo_root=repo_root,
    )
    hidden = normalize_tagged_output(
        raw_text=raw,
        mode="hidden",
        capability=mapped,
        profile=profile,
        runtime="llama.cpp-raw-stdout",
        model_artifact=f"gguf:{artifact_hash}",
        repo_root=repo_root,
    )
    return {
        "pass": visible["reasoning_present"] is True
        and hidden["reasoning_present"] is True
        and hidden["reasoning"] is None
        and mapped.supports_disable is False,
        "transport": "tagged_text",
        "native_reasoning_field": False,
        "supports_hide_via_post_parser": True,
        "supports_disable": False,
        "visible_probe": visible,
        "hidden_probe": hidden,
        "generated_reasoning_quality_claimed": False,
    }


def valid_runtime_output(output: str) -> bool:
    if not output.strip():
        return False
    return not any(ord(ch) < 9 for ch in output)


def task_success(task: Mapping[str, Any], output: str) -> bool:
    if task.get("type") != "exact_answer":
        raise RuntimeParityError(f"unsupported runtime fixture type {task.get('type')}")
    return output.strip() == str(task["expected"]).strip()


def strip_ansi(value: str) -> str:
    return re.sub(r"\x1b\[[0-9;?]*[ -/]*[@-~]", "", value)


def _run(
    command: list[str],
    *,
    cwd: Path | None = None,
    label: str,
    combine: bool = False,
) -> dict[str, Any]:
    completed = subprocess.run(
        command,
        cwd=str(cwd) if cwd else None,
        text=True,
        capture_output=True,
        check=False,
    )
    combined = completed.stdout + ("\n" if completed.stdout and completed.stderr else "") + completed.stderr
    if completed.returncode != 0:
        raise RuntimeParityError(
            f"{label} failed rc={completed.returncode}: {combined[-4000:]}"
        )
    return {
        "returncode": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
        "combined": combined if combine else combined,
        "command_hash": sha256_object(command),
    }


def _read_object(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise RuntimeParityError(f"expected JSON object: {path}")
    return value
